### ISSUE TITLE
proposal: QA checklist?

### ISSUE THREAD

**Issue by Funky185540** [nikhiljha/pp-fedora-sdsetup#102]
Here's a proposal for a QA checklist that could be used to check the github releases for their functionality, i.e. to see which features work and which don't, reproducibly. Maybe it could be added to the Wiki?

Comments/Extensions are welcome!

- The structure of the list is taken from [LineageOS](https://github.com/LineageOS/charter/blob/master/device-support-requirements.md)
- Individual bits were extended given the [Pinephone hardware support](https://pine64.com/product/pinephone-community-edition-manjaro-limited-edition-linux-smartphone-only-eu-order/?v=0446c16e2e66)

-----
## Audio

- [ ] In-call audio works
- [ ] Speaker audio works
- [ ] Headphone audio works (3.5 mm jack)
- [ ] Bluetooth audio works
- [ ] Microphone input works

## Modem

- [ ] Calls work
- [ ] SMS work
- [ ] Mobile data works
- [ ] Emergency Calls without SIM card works

## Encryption

- [ ] Full-Disk-Encryption (FDE) works

## Wi-Fi

- [ ] Wifi connections work
- [ ] Wifi MAC address is read from modem hardware
- [ ] Wifi hotspot works

## USB

- [ ] USB Host mode works
- [ ] File-access over USB (from external device) works
- [ ] DisplayPort output works

## GPS/Location services

- [ ] Location services work
  - [ ] over GPS
  - [ ] over GLONASS
  - [ ] over Mozillas Location Services

## Bluetooth

- [ ] Bluetooth works
- [ ] A2DP (audio streaming profile) works
- [ ] MAC address is read from modem hardware (doesn't change)

## Camera

- Photography works with
  - [ ] Front Camera
  - [ ] Rear Camera
- Video recording works with
  - [ ] Front Camera
  - [ ] Rear Camera

## Sensors

- [ ] Accelerometer
- [ ] Gyroscope
- [ ] Proximity
- [ ] Ambient Light
- [ ] Magnetometer

**Comment by alh61** [comment]
This is actually a good idea. Some of the points we don't have any support for yet, but marking such as n/a is fine.
Nice work.
